apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment #name of the service once created. Use to acces pod
spec:
  selector:
    matchLabels:
      app: flask #app labeled flask
  replicas: 1 # tells deployment to run 1 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: flask
    spec: #task definition for each pod
      containers:
      - name: flask
        image: rixardo/flask:latest
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: LoadBalancer
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 5000
  selector:
    app: flask
